
spring:
  rabbitmq:
    host: 192.168.35.105
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
    # 手动提交消息
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual